R/bed_closest.r, man/bed_closest.Rd, src/closest.cpp, tests/testthat/test_closest.r
=> closest implementation, docs, and tests

R/bed_merge.r
bed_merge giving error with sorted data
=> bed_merge issue with sorted data

R/bed_flank.r, R/bed_merge.r
bed_flank gives wrong start coordinates when strand = T
=> bed_flank bug

R/bed_flank.r, R/bed_slop.r
A couple names were mixed up in bed_flank.  Added rounding for when using fractions with bed_slop.
=> bed_flank and bed_slop

R/bed_closest.r, inst/include/IntervalTree.h, src/closest.cpp, tests/testthat/test_closest.r, vignettes/valr.Rmd
I reimplemented the `closest_impl` algorithm to use the interval tree. The new implementation is much faster, only about 2 times slower than `bed_intersect` with a million `x` and `y` intervals. 
The changes build and pass tests on my machine. 
Here are some speed tests, compared to other functions:
Old `bed_closest` with only a hundred intervals
```
Unit: seconds
expr       min        lq      mean    median        uq       max neval
bed_random(genome) 0.1429224 0.1429224 0.1429224 0.1429224 0.1429224 0.1429224     1
bed_closest(small.x, y) 1.7942209 1.7942209 1.7942209 1.7942209 1.7942209 1.7942209     1
bed_intersect(x, y) 1.3148652 1.3148652 1.3148652 1.3148652 1.3148652 1.3148652     1
bed_merge(x) 2.0511021 2.0511021 2.0511021 2.0511021 2.0511021 2.0511021     1
bed_subtract(x, y) …
```
=> Closest reimpl

vignettes/valr.Rmd
=> minor fixes to vignette (closes #70) 

tests/testthat/test_complement.r, tests/testthat/test_flank.r
=> bed_complement and bed_flank tests 

R/bed_makewindows.r
The `rowwise() %>% do()`  approach in `bed_makewindows()` is particularly slow (4 secs for 1k itervals). This PR implements an approach using list-columns instead of calling `split_interval` per row and substantially speeds up the function. 
Current implementation:
```r
library(valr)
genome <- read_genome(valr_example("genome.txt.gz"))
x <- bed_random(genome, n = 1000)
microbenchmark::microbenchmark(
bed_makewindows(x, genome, win_size = 100),
times = 1,
unit = 's')
#> Unit: seconds
#>                                       expr      min       lq     mean   median
#> bed_makewindows(x, genome, win_size = 100) 4.420829 4.420829 4.420829 4.420829
#>       uq      max neval
#> 4.420829 4.420829     1
```
Updated implementation:
```r
microbenchmark::microbenchmark(
bed_makewindows(x, genome, …
```
=> bed_makewindows(), remove do() implementation, replace with list cols approach

R/bed_makewindows.r
=> fix unnesting failure on rowwise tbls with list cols #165

R/RcppExports.R, R/bed_makewindows.r, src/RcppExports.cpp, src/init.c, src/makewindows.cpp
- to get the speed up
- some tests are wrong and need fixing
=> refactor makewindows

NEWS.md, R/bed_merge.r, docs/news/index.html, docs/reference/bed_merge.html, tests/testthat/test_merge.r
=> report start/end cols when spec is provided to bed_merge()

NEWS.md, R/bed_jaccard.r, R/globals.r, docs/news/index.html, docs/reference/bed_jaccard.html, man/bed_jaccard.Rd, tests/testthat/test_jaccard.r
=> calculate jaccard for grouped inputs

NEWS.md, R/RcppExports.R, R/bed_intersect.r, docs/news/index.html, src/RcppExports.cpp, src/init.c, src/intersect.cpp
- update bed_intersect to remove join-based approach
=> return non-intersecting from intersect_impl

.travis.yml, R/bed_merge.r, R/read_bed.r, R/strands.r, appveyor.yml
- fixes #310 
- Tests pass on [appveyor](https://ci.appveyor.com/project/kriemo/valr/build/1.0.42) and able to build cleanly by also setting _R_CHECK_FORCE_SUGGESTS = 0 (related to krlmlr/r-appveyor#72)
- Also able to get a [clean build](https://travis-ci.org/kriemo/valr/builds/328213887) on travis for devel by explicitly loading devtools (related to travis-ci/travis-ci#8887)
=> issue310 and travis/appveyor fixes

.travis.yml
=> Use xenial for travis

DESCRIPTION, NEWS.md, src/valr_utils.cpp, tests/testthat/test_types.R
Fixed data.frame subsetting to correctly set factor levels and factor class. 
Closes #360
=> allow factors to be returned from cpp side

DESCRIPTION, vignettes/benchmarks.Rmd
Knits fine on my local machine
Performance looks about the same as current plots online
=> #368 bench

NEWS.md, R/features.r, tests/testthat/test_features.r
=> create_introns numbering bug

NEWS.md, src/merge.cpp, tests/testthat/test_cluster.r
=> fix OB1 bug when max_dist argument supplied 

DESCRIPTION, NEWS.md, R/bed_absdist.r, R/bed_closest.r, R/read_bed.r, README.Rmd, README.md, man/read_bed.Rd, tests/testthat/test_closest.r, tests/testthat/test_cluster.r, tests/testthat/test_groups.r, tests/testthat/test_merge.r, tests/testthat/test_read_bed.r, tests/testthat/test_types.R, vignettes/interval-stats.Rmd, vignettes/valr.Rmd
=> sniff n_fields in read_* functions

.github/workflows/check-standard.yaml, .github/workflows/pkgdown.yaml, .github/workflows/pr-commands.yaml, .github/workflows/test-coverage.yaml, README.Rmd, README.md
- **use pkgdown block tags**
- **update gh actions**
=> upkeep v0.8.1
