- src/intersect.cpp
- tests/testthat/test_intersect.r
The `group()` function from `dplyr::SlicingIndex` reports the group index rather than the value of the group.  For intersections where the number of chromosomes are different, this throws off the index numbers, resulting in lost intersections. Issue #44
> Intersect bug

- inst/include/valr.h
- src/closest.cpp
- src/intersect.cpp
- src/substract.cpp
- src/utils.cpp
- tests/testthat/test_subtract.r
* Implemented generic `chromLoop` function in `bed_intersect` and `bed_closest` which loops through `x` and `y` bed files and apply's a supplied function with args (e.g. `intersect_group` and `closest_grouped`) to matched `x` and `y` chromosomes. 
* Fixed a bug in `bed_subtract` in which x intervals were dropped if there was not a matching chromosome in `y` bed.
> Intersect module

- inst/include/IntervalTree.h
- src/closest.cpp
- tests/testthat/test_closest.r
Fix for a minor bug where `bed_closest()` would report duplicate intervals if a certain branch of the code was executed. I also added some tests.
> fix duplicate interval reporting and add tests

- R/bed_flank.r
- R/valr.r
- tests/testthat/test_flank.r
- vignettes/valr.Rmd
Instead of using the `tidyr::gather %>% separate %>% spread` approach, I instead created two tables, one with the `left` and another with the `right` flanking intervals, then joined them together. I also added a test to make sure that all of the `left` and `right` intervals are reported. 
I'll work on rewriting this in `Rcpp` to speed it up. 
This also fixes issue #60.
> fix bed_flank() errors (closes #59 and #60)

- R/bed_closest.r
- tests/testthat/test_closest.r
The bug for `bed_closest()` issue #79 was  because the `closest_impl` did not know the `strand` and therefore would not find the closest stranded interval. The fix subsets the supplied x and y tbls by strand and pass these `closest_imp` . It's a slower implementation, but can be fixed also on the `Cxx` side in the future. 
Speed tests:
```r
microbenchmark::microbenchmark(bed_closest(x, y), unit = 's', times = 1)
Unit: seconds
expr      min       lq     mean   median       uq      max neval
bed_closest(x, y) 3.993389 3.993389 3.993389 3.993389 3.993389 3.993389     1
microbenchmark::microbenchmark(bed_closest(x, y, strand = T), unit = 's', times = 1)
Unit: seconds
expr      min       lq     mean   median       uq      max neval
bed_closest(x, y, strand = T) 10.72268 10.72268 10.72268 …
```
> Additional tests for bed_closest (fixes #79)

- R/bed_shuffle.r
- tests/testthat/test_shuffle.r
In the original `bed_shuffle()` implementation only `chrom` `start` and `end` were returned. This fix will pass any original `x` column supplied that is not shuffled (i.e. `score`, `name`, `strand`) to the result. 
Also, we may want to consider if we need to implement a shuffling procedure for `strand` in the future.
> Shuffle bug fixes #81

- R/bed_map.r
The parameters passed through `...` were overwriting some of the default parameters (invert = FALSE, strand = FALSE, etc.).  I moved the `...` to before the defaults in the function declaration and now all of the examples run. 
Also, there was an issue with the `names_no_x` object, which was pattern matching to a `regex` rather than exactly to the supplied string. For example, the default `x` suffix `.x` would pattern match to a string `max` and convert it to `m`
> Fixed map examples 

- inst/include/IntervalTree.h
- src/closest.cpp
- tests/testthat/test_closest.r
The bug was caused by the recursive fxn `findClosest` which would report back intervals for each function call throughout the recursion. I changed the logic so that it would only report intervals back once a `terminal node` (aka `leaf node`) of the interval tree has been reached. I also clarified some variables and added two additional tests .
> bed_closest bug duplicate interval reporting closes #105

- src/coverage.cpp
- tests/testthat/test_coverage.r
I added a needed method to report intervals back based on the `SlicingIndex` in `coverage.cpp` to address the failed tests in 7f4ad555ea5a9c986665913ba3e0e6df6baa5411. Previously, the `intervals` would be reported back in the same order as the input, which doesn't work with `groups`. All the tests now pass.
> bed_coverage() tests for handling grouping by strands #125

- R/utils.r
- tests/testthat/test_merge.r
- tests/testthat/test_utils.R
I changed `format_bed()` to only reorder columns rather than drop or replace with a dummy variable and added some tests for the bug. 
closes #132
> bed_merge() bug not allowing summaries issue#132

- R/bed_absdist.r
- R/bed_shuffle.r
- man/bed_absdist.Rd
`bed_shuffle()` wasn't returning the result by default. 
The `bed_absdist()` equation was simplified, which has now has no problems on `win_builder`
win_builder output:
https://gist.github.com/kriemo/27bd382a126b7de259624e1b84d8aa91
closes #137 and #138
> bed_absdist() equation and bed_shuffle() reporting 137 138

- NEWS.md
- src/absdist.cpp
When `valgrind` is run on the test suite there is a memory access error in `absdist.cpp`:
```bash
R -d "valgrind --tool=memcheck --dsymutil=yes" --no-readline --vanilla < testthat.R
```
The relevant error
```r
> test_check("valr")
==12828== Invalid read of size 4
==12828==    at 0x1143352BD: absdist_grouped(std::__1::vector<Interval<int, int>, std::__1::allocator<Interval<int, int> > >&, std::__1::vector<Interval<int, int>, std::__1::allocator<Interval<int, int> > >&, std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<float, std::__1::allocator<float> >&) (in /Library/Frameworks/R.framework/Versions/3.3/Resources/library/valr/libs/valr.so)
==12828==    by 0x11433609C: void PairedGroupApply<void (&)(std::__1::vector<Interval<int, int>, std::__1::allocator<Interval<int, …
```
> fix indexing error that was causing a memory-access error

- R/bed_cluster.r
- man/bed_cluster.Rd
- src/merge.cpp
- tests/testthat/test_cluster.r
Tracking the cluster `.id` was easier to implement on the Rcpp side, due to grouping issues. I also added a test and a note in the documentation that `bed_cluster()` requires sorted input.
> track ids independent of groups in bed_cluster #171

- R/bed_cluster.r
- man/bed_cluster.Rd
- src/merge.cpp
- tests/testthat/test_cluster.r
* track ids independent of groups in bed_cluster #171
* sort input by default to avoid additional explict sort
* fixes #171
> track ids independent of groups in bed_cluster

- inst/include/valr.h
- src/merge.cpp
- tests/testthat/test_cluster.r
- tests/testthat/test_merge.r
This PR contains a reimplementation of `merge_impl` which fixes #176 
* The reimplementation is just as fast as the previous implementation
* The tests for `bed_cluster()` were testing for the error, so I fixed the test
* I also added an additional test for `bed_merge()` for contained intervals
```r
x <- tibble::tribble(
~chrom, ~start, ~end,
'chr1',  1,     10,
'chr1',  2,     5,
'chr1',  7,     9
)
bed_merge(x)
#>  # A tibble: 1 × 3
#>    chrom start   end
#>   <chr> <dbl> <dbl>
#>   1  chr1     1    10
```
> Error in bed_shuffle() Issue176

- R/bed_subtract.r
- R/utils.r
- src/subtract.cpp
- tests/testthat/test_subtract.r
For #197 
Major Changes:
- Removed the Cpp code checking for `x` interval groups not found in `y`. This was done by using a join on the R side on the group labels found in `x` and not in `y`. 
- Use`GroupApply` to call`subtract_grouped`. 
Minor Changes:
- Added a utility function `get_labels` which returns the `labels` attribute from `attr()` for grouped tbls. 
For #202 
I was able to speed up `bed_substract()` almost 2x.
Major Changes:
- The two slowest steps for `bed_subtract()` are the calls to `bed_merge()` and `subtract_impl`.  I removed the call to `bed_merge()` on the R-side and instead changed the logic of `subtract_grouped` on the cpp-side to handle overlapping `y` intervals. 
Minor Changes:
- Added a test to check if overlapping y-intervals would be treated as merged. 
```r …
```
> bed_subtract reorganization and profiling #197 and #202

- NEWS.md
- R/bed_intersect.r
- R/bed_makewindows.r
- R/bed_map.r
- R/bed_random.r
- man/bed_map.Rd
- vignettes/interval-stats.Rmd
- vignettes/valr.Rmd
This PR addresses minor changes needed to build `valr` using `dply` at [v.0.6.0-rc](https://github.com/tidyverse/dplyr/releases/tag/v0.6.0-rc)
- `dplyr::everything()` should be quoted in SE dplyr functions (#240)
-  grouped tbls need to be ungrouped prior to unnesting to avoid error in `unnest()`:
``Column `.start`: must be length one (the group size), not 11``
-  `arrange_()` failed to recognized `.dots` argument in `bed_random()` resulting in a failure to sort the output
-  `bind_rows()` in `bed_map()` not accepting list-cols with `tibbles`, but works fine with `lists`
-  passes R CMD check with dplyr v0.5.0 and dplyr v0.6.0-rc
- closes #240 and #242
> dplyr 0.6.0 release compatibility fixes #240

- R/RcppExports.R
- R/bed_cluster.r
- R/bed_merge.r
- inst/include/valr.h
- src/RcppExports.cpp
- src/init.c
- src/merge.cpp
Some improvements to the speed of `bed_merge()`. 
Implemented an internal merge that is very fast. The current bottleneck is the sorting of the input tbl. I'll port this strategy to the rlang branch if this approach looks good. 
Here's a link to the [profiling](http://rpubs.com/kriemo/279213) for running `bed_merge()` on a million random intervals.
Timing for proposed changes:
``` r
library(valr)
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats
genome <- …
```
> speeding up bed_merge() related to  Issue214 and 210

- R/bed_closest.r
- src/closest.cpp
A minor performance gain (~10%) by moving an `ifelse` statement to cpp and adding some preallocation for large vectors. 
``` r
library(valr)
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats
genome <- read_genome(valr_example('hg19.chrom.sizes.gz'))
seed <- 1010486
x <- bed_random(genome, n = 1e6, seed = seed)
y <- bed_random(genome, n = 1e6, seed = seed)
microbenchmark::microbenchmark(bed_closest(x, y), unit = 's', times = 1)
#> Unit: seconds
#>               expr     min      lq    mean  median …
```
> bed_closest() optimization issue210

- R/RcppExports.R
- R/bed_makewindows.r
- src/RcppExports.cpp
- src/init.c
- src/makewindows.cpp
The proposed Cpp implementation is about ~50x faster than the R version. 
The current bed_makewindows() with 1e6 intervals takes ~90 seconds to generate 1e7 intervals.
``` r
library(valr)
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats
genome <- read_genome(valr_example('hg19.chrom.sizes.gz'))
seed <- 1010486
x <- bed_random(genome, n = 1e6, seed = seed)
res <- bed_makewindows(x, genome, win_size = 100)
x
#> # A tibble: 1,000,000 x 3
#>    chrom     start       end
#>    <chr>     <int>     <int> …
```
> speed improvement to bed_makewindows() issue210

- R/RcppExports.R
- R/bed_flank.r
- src/RcppExports.cpp
- src/bed_flank.cpp
- src/init.c
I think I have bed_flank working now. This addresses #237. If the final bed_files are not sorted at the end, this speeds up bed_flank by ~7x. The main bottleneck is the final 'arrange'.
> rewrite bed_flank in C++

- R/RcppExports.R
- R/bed_flank.r
- src/RcppExports.cpp
- src/flank.cpp
Gives a small additional speedup. Code cleanup.
``` r
library(valr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
genome <- read_genome(valr_example('hg19.chrom.sizes.gz'))
x <- bed_random(genome)
microbenchmark(bed_flank(x, genome, both = 100), times = 1, unit = 's')
#> Unit: seconds
#>                              expr      min       lq     mean   median
#>  bed_flank(x, genome, both = 100) 1.144128 1.144128 1.144128 1.144128
#>        uq      max neval
#>  1.144128 1.144128     1
```
> Refactor flank

- src/flank.cpp
- clean R CMD Check on rhub https://builder.r-hub.io/status/valr_0.3.0.tar.gz-9fc565a2aead4bf7974e99ebdbe341c0
- the error was an off by one error, only present in 32-bit R. 
- changed reporting from one-based to zero-based
- closes #277
> OB1 error in bed_flank, issue 277

- NEWS.md
- R/bed_makewindows.r
- man/bed_makewindows.Rd
- src/makewindows.cpp
- tests/testthat/test_makewindows.r
- vignettes/benchmarks.Rmd
- vignettes/valr.Rmd
add warnings to make_windows
- warn and skip interval if num_win is greater than interval size
- deprecate genome argument to bed
- add test for warning and skipped intervals
- remove genome argument from examples and vignettes
- closes #312
> issue312: prevent infinite loop and drop intervals shorter than num_win

- NEWS.md
- src/subtract.cpp
- tests/testthat/test_subtract.r
In some cases `bed_subtract()` does not drop intervals that overlap. This behavior only occurs with larger datasets. This bug is due to assuming that the output from `findOverlaps()` is sorted by coordinate, which is not always true when overlapping intervals are in different nodes of the interval tree.
Below is an example. Calling `bed_subtract()` on the same bed data with ~20k rows returns a small number of intervals that should have been dropped. If the non-dropped intervals are rerun through bed_subtract() now they are successfully dropped. 
``` r
library(valr)
bg <- read_bedgraph(valr_example("hela.h3k4.chip.bg.gz"))
bed_subtract(bg, bg)
#> # A tibble: 479 x 4
#>    chrom    start      end value
#>    <chr>    <int>    <int> <dbl>
#>  1 chr22 17565704 17565724    18
#>  2 chr22 …
```
> bed_subtract() reports overlapping intervals in larger datasets

- NEWS.md
- R/bed_makewindows.r
- src/makewindows.cpp
- tests/testthat/test_makewindows.r
minor changes to `makewindows_impl` to conform with bedtools reporting 
- closes issue #322
> bed_makewindows: require that the same number of requested intervals are always returned

- NEWS.md
- R/bed_glyph.r
- tests/testthat/test_glyph.r
``` r
library(valr)
a <- trbl_interval(
~chrom, ~start, ~end,
'chr1', 25,     50,
'chr1', 100,    125
)
b <- trbl_interval(
~chrom, ~start, ~end, ~value,
'chr1', 30,     75,  50
)
bed_glyph(bed_intersect(a, b))
```
``` r
bed_glyph(bed_intersect(x = a, y = b))
```
Created on 2018-01-24 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).
> bed_glyph: allow x and y arguments to named other than x and y

- NEWS.md
- src/closest.cpp
- tests/testthat/test_closest.r
Distances are now reported correctly for book-ended intervals. The tests have been updated to reflect this fix. The distances reported are now also the same as bedtools closest output. 
closes #311 
``` r
library(valr)
x <- trbl_interval(
~chrom, ~start, ~end,
"chr1", 100,    150
)
y <- trbl_interval(
~chrom, ~start, ~end,
"chr1", 99,     100,
"chr1", 100,    101,
"chr1", 150,    151
)
bed_closest(x, y)
#> # A tibble: 3 x 7
#>   chrom start.x end.x start.y end.y .overlap .dist
#>   <chr>   <dbl> <dbl>   <dbl> <dbl>    <int> <int>
#> 1  chr1     100   150      99   100        0    -1
#> 2  chr1     100   150     100   101        1     0
#> 3  chr1     100   150     150   151        0     1
```
Created on 2018-01-24 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).
> closest behavior on book-ended intervals

- src/makewindows.cpp
- tests/testthat/test_makewindows.r
PR #325 didn't fully resolve the issue of requiring that the number of windows returned is equal to the `num_win` argument. This PR adds explicit iteration logic to handle the `num_win` argument and an additional test. 
Here's a set of intervals that lead to excess windows reported with current implementation. 
``` r
library(valr)
library(dplyr)
x <- tibble::tribble(
~chrom, ~start, ~end,
"chr1", 9437053, 9438070,
"chr1", 75360291, 75368579,
"chr1", 86351980, 86352127
)
res <- bed_makewindows(x, num_win = 100)
res
#> # A tibble: 348 x 4
#>    chrom   start     end .win_id
#>    <chr>   <int>   <int>   <int>
#>  1  chr1 9437053 9437063       1
#>  2  chr1 9437063 9437073       2
#>  3  chr1 9437073 9437083       3
#>  4  chr1 9437083 9437093       4
#>  5  chr1 9437093 9437103       5
#> …
```
> Additional fix for too many windows reported by makewindows

- DESCRIPTION
- R/bed_closest.r
- R/bed_intersect.r
- R/bed_map.r
- R/bed_merge.r
- R/bed_subtract.r
- inst/include/DataFrameBuilder.h
- inst/include/dplyr/data/GroupedDataFrame.h
- inst/include/group_apply.h
- src/api.cpp
- src/dplyr_init.cpp
- src/encoding.cpp
- src/join.cpp
- src/valr_utils.cpp
- tests/testthat/test_factors.R
- tests/testthat/test_groups.r
This PR refactors the `group_apply` function to limit the number of rowwise comparisons necessary prior to applying the function. The `compare_rows` function becomes a bottleneck when there are many groups. 
Intersections are very slow with 1k groups:
``` r
library(valr)
library(tibble)
chrom <- paste0("chr", 1:1e3)
set.seed(42)
start <- sample(1:1e6, 1e3)
end <- start + 1000
bed <- tibble(chrom, start, end)
bed_intersect(bed, bed)
#> # A tibble: 1,000 x 6
#>    chrom   start.x  end.x start.y  end.y .overlap
#>    <chr>     <int>  <dbl>   <int>  <dbl>    <int>
#>  1 chr1     914807 915807  914807 915807     1000
#>  2 chr10    705059 706059  705059 706059     1000
#>  3 chr100   619098 620098  619098 620098     1000
#>  4 chr1000    7411   8411    7411   8411     1000
#>  5 chr101 …
```
> More work on dplyr compatibility and performance gains on tibbles with many groups

- NEWS.md
- inst/include/IntervalTree.h
- tests/testthat/test_closest.r
On current master
``` r
library(valr)
x <- tibble::tribble(
~ chrom, ~ start, ~ end,
"chr1", 10, 20
)
y <- tibble::tribble(
~ chrom, ~ start, ~ end,
"chr1", 8, 9,
"chr1", 9, 10,
"chr1", 20, 21,
"chr1", 21, 22
)
res <- bed_closest(x, y)
res
#> # A tibble: 4 x 7
#>   chrom start.x end.x start.y end.y .overlap .dist
#>   <chr>   <dbl> <dbl>   <dbl> <dbl>    <int> <int>
#> 1 chr1       10    20       9    10        0    -1
#> 2 chr1       10    20      20    21        0     1
#> 3 chr1       10    20       8     9        0    -2
#> 4 chr1       10    20      21    22        0     2
```
<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
With PR:
``` r
library(valr)
x <- tibble::tribble(
~ chrom, ~ start, ~ end,
"chr1", 10, 20
)
y <- tibble::tribble( …
```
>  fix extra interval reporting in bed_closest()

- NEWS.md
- R/bed_random.r
- R/bed_sort.r
- man/bed_random.Rd
- tests/testthat/test_random.r
- vignettes/benchmarks.Rmd
Switching to base R sorting provides a performance gain over `arrange()` and future proofs the code against a regression in dev dplyr that results in a ~30x slow down. This PR also replaces the  sorting code in `bed_random()` with`bed_sort()` to avoid redundancy
Current master performance (CRAN dplyr)
``` r
library(valr)
n <- 1e6
seed_x <- 1010486
genome <- read_genome(valr_example('hg19.chrom.sizes.gz'))
x <- bed_random(genome, n = n, seed = seed_x)
microbenchmark(bed_sort(x),
bed_random(genome, n = n, seed = seed_x),
times = 2,
unit = 's')
#> Unit: seconds
#>                                      expr        min         lq       mean
#>                               bed_sort(x) 0.03779551 0.03779551 0.03914011
#>  bed_random(genome, n = n, seed = seed_x) …
```
> replace arrange with radix sort

- NEWS.md
- src/valr_utils.cpp
I was able to reproduce the error using `rhub::check(platform = 'ubuntu-rchk')`. These changes remove the error. 
closes #365
> rchk unprotect error 

- inst/extdata/bug254_e.bed
- tests/testthat/test_merge.r
in readr 2.0.0 newlines at the end of a file will generate a row of NA
data, rather than being silently ignored. So we needed to modify the
test data to avoid a test failure due to this.
Additionally because readr 2.0.0 uses lazy parsing by default the
warning would not be triggered during the initial read, but instead
later when the malformed value is read. Setting `lazy = FALSE` instead
reads the file eagerly and preserves the expected behavior.
This test needs to be skipped for prior versions of readr,
which don't have the `lazy` parameter.
We plan to submit readr 2.0.0 to CRAN in 3-5 weeks, so you will need to send a release with this change to avoid tests failing on CRAN.
> Updates for readr 2.0.0

- R/bed_random.r
Corrected user feedback for stop() in bed_random. Now it correctly indicates that the issue is "length" being larger than some chrom.sizes.
Should close #385
> Corrected `stop()` message in `bed_random`

- NEWS.md
- src/merge.cpp
- tests/testthat/test_cluster.r
> ensure that first interval per group is part of cluster in bed_cluster

- DESCRIPTION
- NEWS.md
Addresses new CRAN note:
https://cloud.r-project.org/web/checks/check_results_valr.html
We have a Makevars specifying CXX_STD=CXX11, which is best practice and doesn't require SystemRequirements specification:
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-C_002b_002b-code
> remove SystemRequirements from DESCRIPTION

- R/bed_absdist.r
We can safely specify multiple = "all" in `bed_absdist()` to silence this warning. There may be other conditions in other code that trigger this, but I don't see this warning in other tests, examples, or vignettes. 
Note that you need to set `Sys.setenv(TESTTHAT_PKG = "valr")` to see the warning during interactive use. 
closes #399
> specify multiple = "all" argument added in dplyr 1.1.0

- inst/include/grouped_dataframe.h
- src/valr_utils.cpp
this is a cleanup. `r_index` is never used (i.e., it's always set to false), which leads to a compiler warning on os x (`i` is never init in valr_utils.cpp).
> remove `r_index` from df subset fxns

- tests/testthat/test_glyph.r
Hi there,
Apologies for not posting an issue first.
The ggplot2 package is planning an update for around May 2025 and a reverse dependency test identified a problem with the valr package.
The details are explained in https://github.com/tidyverse/ggplot2/issues/6290, but essentially ggplot2 doesn't populate the `plot$labels` field before plot building anymore, which violates some test assumptions in this package.
This PR changes the tests to be compatible with both versions of ggplot2. 
You can test the changes yourself with the development version of ggplot2 (`pak::pak("tidyverse/ggplot2")`)
Best,
Teun
> Compatibility ggplot2 3.6.0
